name: 🚀 Release

on:
  release:
    types: [published]

jobs:
  release:
    name: 🚀 Release
    runs-on: ubuntu-latest
    steps:
      - name: 📚 Checkout
        uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          registry-url: "https://registry.npmjs.org"
          scope: "@shyft-to"
      - name: Install dependencies
        run: npm ci
      - name: 🛠 Build
        run: npm run build
      - name: 🚀 Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      
      - name: 📖 Create the docs directory locally in CI
        run: npm run prepare-doc
      - name: Deploy docs to Github pages 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs
